version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  back:
    # A container that exposes an API to show its IP address
    image: express_demo:latest
    labels:
      - "traefik.http.routers.back.rule=Host(`demo.res.ch`) && PathPrefix(`/api/animals/`)"
      - "traefik.http.routers.back.middlewares=back-stripprefix"
      - "traefik.http.middlewares.back-stripprefix.stripprefix.prefixes=/api/animals/,/api,/api/,/api/animals"
      - "traefik.http.middlewares.back-stripprefix.stripprefix.forceslash=false"
      - "traefik.http.services.back.loadbalancer.server.port=8080"
  front:
    # A container that exposes an API to show its IP address
    image: ajax:latest
    labels:
      - "traefik.http.routers.front.rule=Host(`demo.res.ch`)"
      - "traefik.http.services.front.loadbalancer.server.port=80"
      - "traefik.http.services.front.loadBalancer.sticky.cookie=true"
      - "traefik.http.services.front.loadBalancer.sticky.cookie.name=front_cookie_name"

